### YamlMime:ManagedReference
items:
- uid: Global.TowerCardInfoConfig
  commentId: T:Global.TowerCardInfoConfig
  id: TowerCardInfoConfig
  parent: Global
  children:
  - Global.TowerCardInfoConfig.Damage
  - Global.TowerCardInfoConfig.DamagePerLevel
  - Global.TowerCardInfoConfig.Decription
  - Global.TowerCardInfoConfig.Header
  - Global.TowerCardInfoConfig.Interval
  - Global.TowerCardInfoConfig.IntervalPerLevel
  - Global.TowerCardInfoConfig.Range
  - Global.TowerCardInfoConfig.RangePerLevel
  - Global.TowerCardInfoConfig.TowerStats
  langs:
  - csharp
  - vb
  name: TowerCardInfoConfig
  nameWithType: TowerCardInfoConfig
  fullName: TowerCardInfoConfig
  type: Class
  source:
    id: TowerCardInfoConfig
    path: ''
    startLine: 1460
  assemblies:
  - cs.temp.dll
  namespace: Global
  summary: "\nContains info for tower card ui, such as description, title, damage, etc\nFile name must be same as towerstats file name\n"
  example: []
  syntax:
    content: 'public class TowerCardInfoConfig : ScriptableObject'
    content.vb: >-
      Public Class TowerCardInfoConfig
          Inherits ScriptableObject
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Global.TowerCardInfoConfig.Header
  commentId: F:Global.TowerCardInfoConfig.Header
  id: Header
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: Header
  nameWithType: TowerCardInfoConfig.Header
  fullName: TowerCardInfoConfig.Header
  type: Field
  source:
    id: Header
    path: ''
    startLine: 1463
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Header
    return:
      type: System.String
    content.vb: Public Header As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Global.TowerCardInfoConfig.Decription
  commentId: F:Global.TowerCardInfoConfig.Decription
  id: Decription
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: Decription
  nameWithType: TowerCardInfoConfig.Decription
  fullName: TowerCardInfoConfig.Decription
  type: Field
  source:
    id: Decription
    path: ''
    startLine: 1464
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Decription
    return:
      type: System.String
    content.vb: Public Decription As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Global.TowerCardInfoConfig.Damage
  commentId: P:Global.TowerCardInfoConfig.Damage
  id: Damage
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: Damage
  nameWithType: TowerCardInfoConfig.Damage
  fullName: TowerCardInfoConfig.Damage
  type: Property
  source:
    id: Damage
    path: ''
    startLine: 1465
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Damage { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Damage As String
  overload: Global.TowerCardInfoConfig.Damage*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.DamagePerLevel
  commentId: P:Global.TowerCardInfoConfig.DamagePerLevel
  id: DamagePerLevel
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: DamagePerLevel
  nameWithType: TowerCardInfoConfig.DamagePerLevel
  fullName: TowerCardInfoConfig.DamagePerLevel
  type: Property
  source:
    id: DamagePerLevel
    path: ''
    startLine: 1466
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string DamagePerLevel { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property DamagePerLevel As String
  overload: Global.TowerCardInfoConfig.DamagePerLevel*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.Range
  commentId: P:Global.TowerCardInfoConfig.Range
  id: Range
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: Range
  nameWithType: TowerCardInfoConfig.Range
  fullName: TowerCardInfoConfig.Range
  type: Property
  source:
    id: Range
    path: ''
    startLine: 1467
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Range { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Range As String
  overload: Global.TowerCardInfoConfig.Range*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.RangePerLevel
  commentId: P:Global.TowerCardInfoConfig.RangePerLevel
  id: RangePerLevel
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: RangePerLevel
  nameWithType: TowerCardInfoConfig.RangePerLevel
  fullName: TowerCardInfoConfig.RangePerLevel
  type: Property
  source:
    id: RangePerLevel
    path: ''
    startLine: 1468
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string RangePerLevel { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property RangePerLevel As String
  overload: Global.TowerCardInfoConfig.RangePerLevel*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.Interval
  commentId: P:Global.TowerCardInfoConfig.Interval
  id: Interval
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: Interval
  nameWithType: TowerCardInfoConfig.Interval
  fullName: TowerCardInfoConfig.Interval
  type: Property
  source:
    id: Interval
    path: ''
    startLine: 1469
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Interval { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Interval As String
  overload: Global.TowerCardInfoConfig.Interval*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.IntervalPerLevel
  commentId: P:Global.TowerCardInfoConfig.IntervalPerLevel
  id: IntervalPerLevel
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: IntervalPerLevel
  nameWithType: TowerCardInfoConfig.IntervalPerLevel
  fullName: TowerCardInfoConfig.IntervalPerLevel
  type: Property
  source:
    id: IntervalPerLevel
    path: ''
    startLine: 1470
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string IntervalPerLevel { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property IntervalPerLevel As String
  overload: Global.TowerCardInfoConfig.IntervalPerLevel*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.TowerCardInfoConfig.TowerStats
  commentId: F:Global.TowerCardInfoConfig.TowerStats
  id: TowerStats
  parent: Global.TowerCardInfoConfig
  langs:
  - csharp
  - vb
  name: TowerStats
  nameWithType: TowerCardInfoConfig.TowerStats
  fullName: TowerCardInfoConfig.TowerStats
  type: Field
  source:
    id: TowerStats
    path: ''
    startLine: 1474
  assemblies:
  - cs.temp.dll
  namespace: Global
  summary: "\ninsert tower to automatically gain its stats to description\n"
  example: []
  syntax:
    content: public TowerStats TowerStats
    return:
      type: Global.TowerStats
    content.vb: Public TowerStats As TowerStats
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Global
  name: Global
  nameWithType: Global
  fullName: Global
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Global.TowerCardInfoConfig.Damage*
  commentId: Overload:Global.TowerCardInfoConfig.Damage
  name: Damage
  nameWithType: TowerCardInfoConfig.Damage
  fullName: TowerCardInfoConfig.Damage
- uid: Global.TowerCardInfoConfig.DamagePerLevel*
  commentId: Overload:Global.TowerCardInfoConfig.DamagePerLevel
  name: DamagePerLevel
  nameWithType: TowerCardInfoConfig.DamagePerLevel
  fullName: TowerCardInfoConfig.DamagePerLevel
- uid: Global.TowerCardInfoConfig.Range*
  commentId: Overload:Global.TowerCardInfoConfig.Range
  name: Range
  nameWithType: TowerCardInfoConfig.Range
  fullName: TowerCardInfoConfig.Range
- uid: Global.TowerCardInfoConfig.RangePerLevel*
  commentId: Overload:Global.TowerCardInfoConfig.RangePerLevel
  name: RangePerLevel
  nameWithType: TowerCardInfoConfig.RangePerLevel
  fullName: TowerCardInfoConfig.RangePerLevel
- uid: Global.TowerCardInfoConfig.Interval*
  commentId: Overload:Global.TowerCardInfoConfig.Interval
  name: Interval
  nameWithType: TowerCardInfoConfig.Interval
  fullName: TowerCardInfoConfig.Interval
- uid: Global.TowerCardInfoConfig.IntervalPerLevel*
  commentId: Overload:Global.TowerCardInfoConfig.IntervalPerLevel
  name: IntervalPerLevel
  nameWithType: TowerCardInfoConfig.IntervalPerLevel
  fullName: TowerCardInfoConfig.IntervalPerLevel
- uid: Global.TowerStats
  commentId: T:Global.TowerStats
  name: TowerStats
  nameWithType: TowerStats
  fullName: TowerStats
