### YamlMime:ManagedReference
items:
- uid: Global.WorldCellCardInfoConfig
  commentId: T:Global.WorldCellCardInfoConfig
  id: WorldCellCardInfoConfig
  parent: Global
  children:
  - Global.WorldCellCardInfoConfig.CellStats
  - Global.WorldCellCardInfoConfig.CellTags
  - Global.WorldCellCardInfoConfig.Decription
  - Global.WorldCellCardInfoConfig.Header
  langs:
  - csharp
  - vb
  name: WorldCellCardInfoConfig
  nameWithType: WorldCellCardInfoConfig
  fullName: WorldCellCardInfoConfig
  type: Class
  source:
    id: WorldCellCardInfoConfig
    path: ''
    startLine: 1566
  assemblies:
  - cs.temp.dll
  namespace: Global
  summary: "\nContains info for world cell card ui, such as description, title, types, etc\nFile name must be same as towerstats file name\n"
  example: []
  syntax:
    content: 'public class WorldCellCardInfoConfig : ScriptableObject'
    content.vb: >-
      Public Class WorldCellCardInfoConfig
          Inherits ScriptableObject
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Global.WorldCellCardInfoConfig.Header
  commentId: F:Global.WorldCellCardInfoConfig.Header
  id: Header
  parent: Global.WorldCellCardInfoConfig
  langs:
  - csharp
  - vb
  name: Header
  nameWithType: WorldCellCardInfoConfig.Header
  fullName: WorldCellCardInfoConfig.Header
  type: Field
  source:
    id: Header
    path: ''
    startLine: 1569
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Header
    return:
      type: System.String
    content.vb: Public Header As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Global.WorldCellCardInfoConfig.Decription
  commentId: F:Global.WorldCellCardInfoConfig.Decription
  id: Decription
  parent: Global.WorldCellCardInfoConfig
  langs:
  - csharp
  - vb
  name: Decription
  nameWithType: WorldCellCardInfoConfig.Decription
  fullName: WorldCellCardInfoConfig.Decription
  type: Field
  source:
    id: Decription
    path: ''
    startLine: 1570
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string Decription
    return:
      type: System.String
    content.vb: Public Decription As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Global.WorldCellCardInfoConfig.CellTags
  commentId: P:Global.WorldCellCardInfoConfig.CellTags
  id: CellTags
  parent: Global.WorldCellCardInfoConfig
  langs:
  - csharp
  - vb
  name: CellTags
  nameWithType: WorldCellCardInfoConfig.CellTags
  fullName: WorldCellCardInfoConfig.CellTags
  type: Property
  source:
    id: CellTags
    path: ''
    startLine: 1571
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public string CellTags { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property CellTags As String
  overload: Global.WorldCellCardInfoConfig.CellTags*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Global.WorldCellCardInfoConfig.CellStats
  commentId: F:Global.WorldCellCardInfoConfig.CellStats
  id: CellStats
  parent: Global.WorldCellCardInfoConfig
  langs:
  - csharp
  - vb
  name: CellStats
  nameWithType: WorldCellCardInfoConfig.CellStats
  fullName: WorldCellCardInfoConfig.CellStats
  type: Field
  source:
    id: CellStats
    path: ''
    startLine: 1577
  assemblies:
  - cs.temp.dll
  namespace: Global
  summary: "\ninsert cell to automatically gain its stats to description\n"
  example: []
  syntax:
    content: public CellStats CellStats
    return:
      type: Services.CardGeneration.CellStats
    content.vb: Public CellStats As CellStats
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Global
  name: Global
  nameWithType: Global
  fullName: Global
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Global.WorldCellCardInfoConfig.CellTags*
  commentId: Overload:Global.WorldCellCardInfoConfig.CellTags
  name: CellTags
  nameWithType: WorldCellCardInfoConfig.CellTags
  fullName: WorldCellCardInfoConfig.CellTags
- uid: Services.CardGeneration.CellStats
  commentId: T:Services.CardGeneration.CellStats
  parent: Services.CardGeneration
  name: CellStats
  nameWithType: CellStats
  fullName: Services.CardGeneration.CellStats
- uid: Services.CardGeneration
  commentId: N:Services.CardGeneration
  name: Services.CardGeneration
  nameWithType: Services.CardGeneration
  fullName: Services.CardGeneration
