### YamlMime:ManagedReference
items:
- uid: Services.CardGeneration.WorldCellCardsConfig
  commentId: T:Services.CardGeneration.WorldCellCardsConfig
  id: WorldCellCardsConfig
  parent: Services.CardGeneration
  children:
  - Services.CardGeneration.WorldCellCardsConfig.Configs
  langs:
  - csharp
  - vb
  name: WorldCellCardsConfig
  nameWithType: WorldCellCardsConfig
  fullName: Services.CardGeneration.WorldCellCardsConfig
  type: Class
  source:
    id: WorldCellCardsConfig
    path: ''
    startLine: 1809
  assemblies:
  - cs.temp.dll
  namespace: Services.CardGeneration
  syntax:
    content: 'public class WorldCellCardsConfig : ScriptableObject'
    content.vb: >-
      Public Class WorldCellCardsConfig
          Inherits ScriptableObject
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Services.CardGeneration.WorldCellCardsConfig.Configs
  commentId: F:Services.CardGeneration.WorldCellCardsConfig.Configs
  id: Configs
  parent: Services.CardGeneration.WorldCellCardsConfig
  langs:
  - csharp
  - vb
  name: Configs
  nameWithType: WorldCellCardsConfig.Configs
  fullName: Services.CardGeneration.WorldCellCardsConfig.Configs
  type: Field
  source:
    id: Configs
    path: ''
    startLine: 1812
  assemblies:
  - cs.temp.dll
  namespace: Services.CardGeneration
  syntax:
    content: public TowerToWorldCellPair[] Configs
    return:
      type: Services.CardGeneration.TowerToWorldCellPair[]
    content.vb: Public Configs As TowerToWorldCellPair()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Services.CardGeneration
  commentId: N:Services.CardGeneration
  name: Services.CardGeneration
  nameWithType: Services.CardGeneration
  fullName: Services.CardGeneration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Services.CardGeneration.TowerToWorldCellPair[]
  isExternal: true
  name: TowerToWorldCellPair[]
  nameWithType: TowerToWorldCellPair[]
  fullName: Services.CardGeneration.TowerToWorldCellPair[]
  nameWithType.vb: TowerToWorldCellPair()
  fullName.vb: Services.CardGeneration.TowerToWorldCellPair()
  name.vb: TowerToWorldCellPair()
  spec.csharp:
  - uid: Services.CardGeneration.TowerToWorldCellPair
    name: TowerToWorldCellPair
    nameWithType: TowerToWorldCellPair
    fullName: Services.CardGeneration.TowerToWorldCellPair
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: Services.CardGeneration.TowerToWorldCellPair
    name: TowerToWorldCellPair
    nameWithType: TowerToWorldCellPair
    fullName: Services.CardGeneration.TowerToWorldCellPair
  - name: ()
    nameWithType: ()
    fullName: ()
