### YamlMime:ManagedReference
items:
- uid: Services
  commentId: N:Services
  id: Services
  children:
  - Services.AbstractSoundPlayerService
  - Services.DamageTextService
  - Services.GameTimeService
  - Services.SimpleSoundPlayerService
  langs:
  - csharp
  - vb
  name: Services
  nameWithType: Services
  fullName: Services
  type: Namespace
  assemblies:
  - cs.temp.dll
references:
- uid: Services.DamageTextService
  commentId: T:Services.DamageTextService
  name: DamageTextService
  nameWithType: DamageTextService
  fullName: Services.DamageTextService
- uid: Services.GameTimeService
  commentId: T:Services.GameTimeService
  name: GameTimeService
  nameWithType: GameTimeService
  fullName: Services.GameTimeService
- uid: Services.AbstractSoundPlayerService
  commentId: T:Services.AbstractSoundPlayerService
  parent: Services
  name: AbstractSoundPlayerService
  nameWithType: AbstractSoundPlayerService
  fullName: Services.AbstractSoundPlayerService
- uid: Services.SimpleSoundPlayerService
  commentId: T:Services.SimpleSoundPlayerService
  name: SimpleSoundPlayerService
  nameWithType: SimpleSoundPlayerService
  fullName: Services.SimpleSoundPlayerService
- uid: Services
  commentId: N:Services
  name: Services
  nameWithType: Services
  fullName: Services
